In [7]:
import pandas as pd
data=[["Rahim",12],["korim",32],["abul",22]]
df=pd.DataFrame(data,columns=("Name","Age"))
print(df)

    Name  Age
0  Rahim   12
1  korim   32
2   abul   22

In [8]:
df.to_csv("mydata")

### Import data from other files

In [14]:
df=pd.read_csv("export data.csv")
df.head()
df
df.tail()

    Year   Export  Import      FDI     GDP
34  2015  31209.0   40704  2235.39  195080
35  2016  34257.0   43122  2332.72  221420
36  2017  34656.0   47005  2151.56  249710
37  2018  36668.0   58865  3613.30  274040
38  2019  40535.0   59915  2873.95  302570

In [15]:
df.shape

(39, 5)

In [19]:
df.info()
df["Export"].count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    39 non-null     int64
 1   Export  39 non-null     float64
 2   Import  39 non-null     int64
 3   FDI     39 non-null     float64
 4   GDP     39 non-null     int64
dtypes: float64(2), int64(3)
memory usage: 1.7 KB

39

### slicing from data from

In [24]:
print(df.iloc[20:33])

    Year   Export  Import      FDI     GDP
20  2001   6467.0    9335   354.47   53990
21  2002   5986.0    8540   335.47   54720
22  2003   6548.0    9658   350.25   60160
23  2004   7603.0   10903   460.40   65110
24  2005   8654.5   13147   845.26   69440
25  2006  10526.0   14746   792.48   71820
26  2007  12178.0   17157   666.36   79610
27  2008  14111.0   21629  1086.31   91630
28  2009  15565.0   22507   700.16  102480
29  2010  16205.0   23738   913.32  115280
30  2011  22928.0   33658  1136.38  128640
31  2012  24302.0   35516  1292.56  133360
32  2013  27027.0   35084  1599.16  149990

In [25]:
print(df.loc[20:33])

    Year   Export  Import      FDI     GDP
20  2001   6467.0    9335   354.47   53990
21  2002   5986.0    8540   335.47   54720
22  2003   6548.0    9658   350.25   60160
23  2004   7603.0   10903   460.40   65110
24  2005   8654.5   13147   845.26   69440
25  2006  10526.0   14746   792.48   71820
26  2007  12178.0   17157   666.36   79610
27  2008  14111.0   21629  1086.31   91630
28  2009  15565.0   22507   700.16  102480
29  2010  16205.0   23738   913.32  115280
30  2011  22928.0   33658  1136.38  128640
31  2012  24302.0   35516  1292.56  133360
32  2013  27027.0   35084  1599.16  149990
33  2014  30187.0   40732  1551.38  172890

In [26]:
df[["Year","Export"]]

    Year    Export
0   1981    709.85
1   1982    625.89
2   1983    686.60
3   1984    810.99
4   1985    934.43
5   1986    819.21
6   1987   1073.80
7   1988   1231.20
8   1989   1291.60
9   1990   1523.70
10  1991   1717.60
11  1992   1993.90
12  1993   2382.90
13  1994   2533.90
14  1995   3472.60
15  1996   3882.40
16  1997   4418.30
17  1998   5161.20
18  1999   5312.90
19  2000   5752.20
20  2001   6467.00
21  2002   5986.00
22  2003   6548.00
23  2004   7603.00
24  2005   8654.50
25  2006  10526.00
26  2007  12178.00
27  2008  14111.00
28  2009  15565.00
29  2010  16205.00
30  2011  22928.00
31  2012  24302.00
32  2013  27027.00
33  2014  30187.00
34  2015  31209.00
35  2016  34257.00
36  2017  34656.00
37  2018  36668.00
38  2019  40535.00

In [27]:
df.describe()

              Year        Export        Import          FDI            GDP
count    39.000000     39.000000     39.000000    39.000000      39.000000
mean   2000.000000  11075.581282  16280.000000   832.256410   82212.307692
std      11.401754  12237.044791  16858.429734   809.611718   76571.647579
min    1981.000000    625.890000   2540.000000   231.610000   17610.000000
25%    1990.500000   1620.650000   3518.000000   321.000000   29870.000000
50%    2000.000000   5752.200000   8540.000000   356.000000   53370.000000
75%    2009.500000  15885.000000  23122.500000   999.815000  108880.000000
max    2019.000000  40535.000000  59915.000000  3613.300000  302570.000000

In [34]:
df1=pd.read_csv("hart_disease.csv")
df1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

### new data form data Frame

In [39]:
df11=df1[["age","sex","cp"]]
df11
df11[5:44]
df11.shape

(303, 3)

In [41]:
df11.tail()

     age  sex  cp
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

### Assignment10 From be reasercher

In [42]:
rainfal=pd.read_csv("rainfal_data.csv")

In [43]:
print(rainfal)

      Station_Names  YEAR  Month  Temprature    Rainfall
0             Bogra  1948      1        25.8    8.140625
1             Bogra  1948      2        33.3   11.140625
2             Bogra  1948      3        38.3   25.312500
3             Bogra  1948      4        39.5   69.140625
4             Bogra  1948      5        36.1  179.890625
...             ...   ...    ...         ...         ...
21115        Teknaf  2013      8        32.5  851.000000
21116        Teknaf  2013      9        32.6  329.000000
21117        Teknaf  2013     10        33.1  271.000000
21118        Teknaf  2013     11        32.5    0.000000
21119        Teknaf  2013     12        29.9    0.000000

[21120 rows x 5 columns]

In [44]:
rainfal.shape

(21120, 5)

In [47]:
rainfal.describe()

               YEAR         Month    Temprature      Rainfall
count  21120.000000  21120.000000  21120.000000  21120.000000
mean    1985.773295      6.500000     33.475129    197.529667
std       17.604499      3.452134      2.986268    239.041031
min     1948.000000      1.000000     21.600000      0.000000
25%     1972.000000      3.750000     31.700000      8.000000
50%     1988.000000      6.500000     33.900000    110.000000
75%     2001.000000      9.250000     35.500000    310.000000
max     2013.000000     12.000000     44.000000   2072.000000